class VKAuthError(Exception):
    def __init__(self):
        pass
